export const modelStyle = {
    time: document.getElementsByClassName('time'),
    main: document.getElementsByClassName('chat__chat'),
    header: document.getElementsByClassName('chat__header'),
    footer: document.getElementsByClassName('chat__footer'),
    isWhite: false,
    btnSend: document.getElementsByClassName('form__btn'),
    userMsg: document.getElementsByClassName('user-msg__msg'),
    history: document.getElementsByClassName('main__message'),
    otherMsg: document.getElementsByClassName('other-msg__msg'),
    otherMsgAfter: document.getElementsByClassName('other-msg'),
    userMsgAfter: document.getElementsByClassName('user-msg'),
    nickname: document.getElementsByClassName('nickname'),
    inputField: document.getElementsByClassName('form__input'),
    modalTitle: document.getElementsByClassName('nickname__title'),
    modalInput: document.getElementById('nickNameInput'),
    modalBtnSend: document.getElementsByClassName('nickname__btn'),
    idUserLenght: document.getElementById('users'),
    modalBackground: document.getElementsByClassName('modal__nickname'),
    btnChangeWhiteTheme: document.getElementById('white-theme'),
    btnChangeBlackTheme: document.getElementById('black-theme'),
    backgroundUserOnline: document.getElementsByClassName('header__users'),
};
